add_subdirectory(GameEngine)
add_subdirectory(GameEngineDevice)
add_subdirectory(Libraries/Source/Benchmark)
add_subdirectory(Libraries/Source/Bink)
add_subdirectory(Libraries/Source/Compression)
add_subdirectory(Libraries/Source/debug)
add_subdirectory(Libraries/Source/dx8)
add_subdirectory(Libraries/Source/EABrowserDispatch)
add_subdirectory(Libraries/Source/GameSpy)
add_subdirectory(Libraries/Source/Miles6)
add_subdirectory(Libraries/Source/profile)
add_subdirectory(Libraries/Source/WWVegas/WW3D2)
add_subdirectory(Libraries/Source/WWVegas/WWDebug)
add_subdirectory(Libraries/Source/WWVegas/WWDownload)
add_subdirectory(Libraries/Source/WWVegas/WWLib)
add_subdirectory(Libraries/Source/WWVegas/WWMath)
add_subdirectory(Libraries/Source/WWVegas/WWSaveLoad)
add_subdirectory(Libraries/Source/WWVegas/WWShade)
add_subdirectory(Libraries/Source/WWVegas/WWUtil)

add_subdirectory(Main)
